### ISSUE TITLE
Error Reconciling RestDefinition: Missing Components and Improper File Path Resolution in `oasgen-provider`

### ISSUE THREAD

**Issue by banshee86vr** [krateoplatformops/oasgen-provider#30]
**Describe the bug**  
The `oasgen-provider` (Kubernetes operator) managing the `RestDefinition` for `github-runnergroup` fails to reconcile due to missing components in the specification and improperly resolved file paths. The error suggests that `rolodex` is unable to open required files because it lacks proper base configuration.

**To Reproduce**  
1. Deploy the following `RestDefinition` manifest:

   ```yaml
   kind: RestDefinition
   apiVersion: swaggergen.krateo.io/v1alpha1
   metadata:
     name: github-runnergroup
     namespace: gh-runners
   spec:
     oasPath: https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions-next/ghec/dereferenced/ghec.deref.yaml
     resourceGroup: github.customer.com
     resource:
       kind: RunnerGroup
       identifiers:
         - enterprise
         - runner_group_id
       verbsDescription:
         - action: findby
           method: GET
           path: /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}
         - action: get
           method: GET
           path: /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}
         - action: update
           method: PATCH
           path: /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}
         - action: create
           method: POST
           path: /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}
   ```

2. Wait for the `oasgen-provider` to reconcile the resource.

3. Observe the error logs in the operator.

**Expected behavior**  
The `oasgen-provider` should successfully reconcile the `RestDefinition` without errors, and the specified resources should be managed correctly.

**Error Log**  
```
2024-11-19T08:18:13Z	DEBUG	oas-gen-provider	Reconciling	{"controller": "managed/restdefinition.swaggergen.krateo.io", "request": {"name":"github-runnergroup","namespace":"gh-runners"}}
{"time":"2024-11-19T08:18:18.017224341Z","level":"ERROR","msg":"unable to open the rolodex file, check specification references and base path","file":"/go/server-statistics-advisory-db.yaml","error":"rolodex has no file systems configured, cannot open '/go/server-statistics-advisory-db.yaml'. Add a BaseURL or BasePath to your configuration so the rolodex knows how to resolve references"}
{"time":"2024-11-19T08:18:18.017249368Z","level":"ERROR","msg":"unable to open the rolodex file, check specification references and base path","file":"/go/server-statistics-actions.yaml","error":"rolodex has no file systems configured, cannot open '/go/server-statistics-actions.yaml'. Add a BaseURL or BasePath to your configuration so the rolodex knows how to resolve references"}
{"time":"2024-11-19T08:18:18.017249599Z","level":"ERROR","msg":"unable to open the rolodex file, check specification references and base path","file":"/go/server-statistics-packages.yaml","error":"rolodex has no file systems configured, cannot open '/go/server-statistics-packages.yaml'. Add a BaseURL or BasePath to your configuration so the rolodex knows how to resolve references"}
2024-11-19T08:18:18Z	DEBUG	oas-gen-provider	Cannot connect to provider	{"controller": "managed/restdefinition.swaggergen.krateo.io", "request": {"name":"github-runnergroup","namespace":"gh-runners"}, "uid": "3e3fa8eb-0c20-4401-aeb6-ed4a19fef881", "version": "37248357", "external-name": "", "error": "failed to build model: component 'server-statistics-advisory-db.yaml' does not exist in the specification\ncomponent 'server-statistics-actions.yaml' does not exist in the specification\ncomponent 'server-statistics-packages.yaml' does not exist in the specification"}
2024-11-19T08:18:18Z	DEBUG	events	failed to build model: component 'server-statistics-advisory-db.yaml' does not exist in the specification
component 'server-statistics-actions.yaml' does not exist in the specification
component 'server-statistics-packages.yaml' does not exist in the specification	{"type": "Warning", "object": {"kind":"RestDefinition","namespace":"gh-runners","name":"github-runnergroup","uid":"3e3fa8eb-0c20-4401-aeb6-ed4a19fef881","apiVersion":"swaggergen.krateo.io/v1alpha1","resourceVersion":"37248357"}, "reason": "CannotConnectToProvider"}
2024-11-19T08:18:18Z	DEBUG	oas-gen-provider	Reconciling	{"controller": "managed/restdefinition.swaggergen.krateo.io", "request": {"name":"github-runnergroup","namespace":"gh-runners"}}
```

**Additional context**  
The error indicates that certain components (`server-statistics-advisory-db.yaml`, `server-statistics-actions.yaml`, `server-statistics-packages.yaml`) are referenced but do not exist in the specification. This might be due to an incorrect or incomplete `oasPath` in the `RestDefinition` spec. Additionally, the `rolodex` tool needs a properly configured `BaseURL` or `BasePath` to resolve file references correctly.

**Comment by banshee86vr** [comment]
In the meantime, I'm trying to extract a subset of paths from the GitHub REST API's OpenAPI schema and use it with the generator

**Comment by matteogastaldello** [comment]
Hi Luca! 
Until now, it has been a good idea to have a subset of the endpoints you need for generating the controller in a separate OpenAPI specification, because the generator is not able to retrieve references from other locations.
Note that sometimes examples are referenced from other locations but can be removed from the specification, as they are not needed by the generator.

**Comment by banshee86vr** [comment]
Ciao Matteo,
I’ve extracted everything I needed from GitHub's OpenAPI Swagger specification, and you can find the resulting specification here: [GitHub Runner Group Swagger](https://github.com/banshee86vr/github-runner-group-swagger/blob/main/ghec_extracted.yaml).

Here’s the updated manifest I’m using:

```yaml
kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: github-runnergroup
  namespace: gh-runners
spec:
  oasPath: https://raw.githubusercontent.com/banshee86vr/github-runner-group-swagger/refs/heads/main/ghec_extracted.yaml
  resourceGroup: github.customer.com
  resource:
    kind: RunnerGroup
    identifiers:
      - org
      - runner_group_id
    verbsDescription:
      - action: findby
        method: GET
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: get
        method: GET
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: update
        method: PATCH
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: create
        method: POST
        path: /orgs/{org}/actions/runner-groups
      - action: delete
        method: DELETE
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
```

Unfortunately, I’ve encountered some issues with the provider:

---

### **1. Initial Warnings**

When the `RestDefinition` resource is applied, the provider logs these messages:

```plaintext
2024-11-19T13:54:08Z	DEBUG	oas-gen-provider	Reconciling	{"controller": "managed/restdefinition.swaggergen.krateo.io", "request": {"name":"github-runnergroup","namespace":"gh-runners"}}
2024-11-19T13:54:08Z	DEBUG	oas-gen-provider	cannot determine creation result - remove the krateo.io/external-create-pending annotation if it is safe to proceed	{"controller": "managed/restdefinition.swaggergen.krateo.io", "request": {"name":"github-runnergroup","namespace":"gh-runners"}, "uid": "8bee0557-38d4-4142-8776-fcc71d3057c1", "version": "37388671", "external-name": ""}
2024-11-19T13:54:08Z	DEBUG	events	cannot determine creation result - remove the krateo.io/external-create-pending annotation if it is safe to proceed	{"type": "Warning", "object": {"kind":"RestDefinition","namespace":"gh-runners","name":"github-runnergroup","uid":"8bee0557-38d4-4142-8776-fcc71d3057c1","apiVersion":"swaggergen.krateo.io/v1alpha1","resourceVersion":"37388671"}, "reason": "CannotInitializeManagedResource"}
```

---

### **2. Behavior After Removing the Annotation**

When I remove the `krateo.io/external-create-pending` annotation as suggested, the provider crashes with the following panic:

```plaintext
2024-11-19T14:15:37Z	ERROR	Observed a panic	{"controller": "managed/restdefinition.swaggergen.krateo.io", "controllerGroup": "swaggergen.krateo.io", "controllerKind": "RestDefinition", "RestDefinition": {"name":"github-runnergroup","namespace":"gh-runners"}, "namespace": "gh-runners", "name": "github-runnergroup", "reconcileID": "269eaf5f-65cd-4673-89b7-dae369c2e20c", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory address or nil pointer dereference\"", "stacktrace": "goroutine 16 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x22b6a98, 0xc00dd1b0b0}, {0x1c71000, 0x336e490})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:105 +0x112\npanic({0x1c71000?, 0x336e490?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/krateoplatformops/oasgen-provider/internal/controllers/restdefinition/generator.GenerateByteSchemas(0xc0001ad740, {{0xc0020d2dc0, 0xb}, {0xc00061cc60, 0x5, 0x6}, {0xc00f4050c0, 0x2, 0x4}}, {0xc00f4050c0, ...})\n\t/src/internal/controllers/restdefinition/generator/oas.go:145 +0x23a5\ngithub.com/krateoplatformops/oasgen-provider/internal/controllers/definition.(*external).Create(0xc00f404e80, {0x22b6b40, 0xc0003b8230}, {0x22dc4e0?, 0xc0002a6780})\n\t/src/internal/controllers/definition/definition.go:242 +0x25c\ngithub.com/krateoplatformops/provider-runtime/pkg/reconciler.(*Reconciler).Reconcile(0xc00029a5a0, {0x22b6a98, 0xc00dd1b0b0}, {{{0xc00f506c20, 0xa}, {0xc007a0c198, 0x12}}})\n\t/go/pkg/mod/github.com/krateoplatformops/provider-runtime@v0.9.0/pkg/reconciler/reconciler.go:716 +0x42a4\ngithub.com/krateoplatformops/provider-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc000181b80, {0x22b6a98, 0xc00dd1b0b0}, {{{0xc00f506c20?, 0x1f85952?}, {0xc007a0c198?, 0x100?}}})\n\t/go/pkg/mod/github.com/krateoplatformops/provider-runtime@v0.9.0/pkg/ratelimiter/reconciler.go:38 +0x151\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc00dd1afc0?, {0x22b6a98?, 0xc00dd1b0b0?}, {{{0xc00f506c20?, 0x0?}, {0xc007a0c198?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x22cc9e0, {0x22b6ad0, 0xc0001806e0}, {{{0xc00f506c20, 0xa}, {0xc007a0c198, 0x12}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303 +0x3a5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x22cc9e0, {0x22b6ad0, 0xc0001806e0})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263 +0x20e\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 73\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:220 +0x490\n"}
```

---

### **Analysis**

The crash occurs in the `GenerateByteSchemas` function while resolving schemas, likely due to an invalid memory address or nil pointer dereference.
